### PR TITLE
Modernize Hovor

### LINKED ISSUE #7: Modernize Hovor for the MuLab Era
- [x] Remove all reliance on Watson tech (in lieu of generic local DB access)
- [x] Top-level directory cleanup
- [x] Have both in-mem + persistent storage options for the conversations
- [x] Encapsulate things so that running is a single agent -- should be turn-key and dockerized (takes in the generated agent info -- json and plan)

### PR DESCRIPTION
**Pull request by beckydvn**
Closes #7.

@jlaframboise This allows hovor to be run with Docker which allows for persistent conversations (more details in README :smiley:)

Apologies for the 105 files changed. It's only because I had to change the directory structure :P

### CODE REVIEW

**Comment by haz** [comment]
This something that's still in flux, or one I can start looking through?

**Comment by beckydvn** [comment]
@haz It's good to go now, thanks!

**Comment by haz** [comment]
image

**Comment by haz** [comment]
Looks like there are merge conflicts now?

I think the system has gotten to a point where the diffs are too big to be meaningful. Only thing to do now is a full code audit ;). We'll set something up for late April / early May.

**Comment by beckydvn** [comment]
Ah, those weren't there before, I guess new stuff has merged in. I'll look into it now :)

**Comment by beckydvn** [comment]
All done!

**Comment by beckydvn** [comment]
Yeesh, looks like Tensorflow is having a bad day...

image

**Comment by haz** [comment]
Should I hold off on things until you can throw in updated tf stuff?

As a separate note, I think we should have a sprint this summer to streamline plan4dial. Tis a beast to build from scratch ;).

**Comment by beckydvn** [comment]
I'm not sure what's going on with TF -- I don't use it directly, it's just used by Rasa to train things. Might be a versioning thing so I'll look into that :)

**Comment by beckydvn** [comment]
Streamline as in, dockerize? (Should have that already). Or do you mean with writing the YAML?

**Comment by haz** [comment]
> Streamline as in, dockerize? (Should have that already). Or do you mean with writing the YAML?

Neither, actually. I mean bringing the size of (and time to compile) the image way down. A light-weight plan4dial, if you will ;)

**Comment by haz** [comment]
So I'm going to merge this now -- in lieu of a code review we'll do a deep dive in the summer (w/ Victoria and maybe some others). Added an issue for streamlining things [here](https://github.com/dialogue-planning/contingent-plan-executor/issues/15), and let me know if you figure out what's up with the TF issues.

**Comment by beckydvn** [comment]
Sounds good -- still in the midst of figuring out the TF thing :'(

**Pull request merged**
